function enterBatchProcessingUnitCode(){
	var reportName = $("#reportName").val();

//other trade
	if(reportName=='APOthersReport'){
		APOthersReport(); 
	}
	if(reportName=='AROthersReport'){
		AROthersReport(); 
	}
	if(reportName=='monthlyTransactionCount'){
		generateMonthlyTransactionCountReport(); 
	}
	if(reportName=='ytdTransactionCountImportExport'){
		generateYtdTransactionCountImportExportReport(); 
	}
	if(reportName=='dailSummOfAccEntry'){
		generaterunDailySummaryOfAccountingEntries(); 
	}
	if(reportName=='weeklyScheduleDocStamps'){
		generateWeeklyScheduleDocStampsReport(); 
	}
	if(reportName=='listOfTransactionsWithNoCifNumber'){
		generateListOfTransactionsWithNoCifNumberReport(); 
	}
	if(reportName=='profitabilityMonitoringExceptionReport'){
		generateProfitabilityMonitoringReport('exception'); 
	}
	if(reportName=='profitabilityMonitoringReport'){
		generateProfitabilityMonitoringReport('notException'); 
	}
	if(reportName=='tfsCasaPostingReport'){
		generateTfsCasaPostingReport(); 
	}
	if(reportName=='collectedTwoPercentCwt'){
		generateCollectedTwoPercentCwtReport(); 
	}
	if(reportName=='productAvailmentsExceptionReport'){
		generateProductAvailmentsReport('exception'); 
	}
	if(reportName=='productAvailmentsReport'){
		generateProductAvailmentsReport('notException'); 
	}
	if(reportName=='dwExceptionReport'){
		generateDwExceptionReport(); 
	}
	if(reportName=='amlaReportedTransactions'){
		amlaReportedTransactions(); 
	}
	if(reportName=='volumetrics'){
		generateVolumetricsReport(); 
	}
	
//other imports
	if(reportName=='outstandingBankGuaranty'){
		outstandingBankGuaranty(); 
		}
	if(reportName=='OutstandingMarginalDeposit'){
		OutstandingMarginalDeposit(); 
		}
	
//non-LC
	if(reportName=='dmNonLcNegofortheYear'){
		dmNonLcNegofortheYear(); 
		}
	if(reportName=='fxnonLcNegofortheYear'){
		fxnonLcNegofortheYear(); 
		}
	if(reportName=='outstandingInwardBillsCollectionDM'){
		outstandingInwardBillsCollectionDM(); 
		}
	if(reportName=='OutstandingInwardBillsCollectionFX'){
		OutstandingInwardBillsCollectionFX(); 
		}
	
// dmlc
	if(reportName=='consolidatedReportDmlcOpenedForTheMonth'){
		consolidatedReportDmlcOpenedForTheMonth(); 
		}
	if(reportName=='dmlcOpenedfortheMonth'){
		dmlcOpenedfortheMonth(); 
		}
	if(reportName=='outsDmlcCashperCurr'){
		outsDmlcCashperCurr(); 
		}
	if(reportName=='outDmlcCashperImporter'){
		outDmlcCashperImporter(); 
		}
	if(reportName=='outDmlcSightperCurr'){
		outDmlcSightperCurr(); 
		}
	if(reportName=='outDmlcSightperImporter'){
		outDmlcSightperImporter(); 
		}
	if(reportName=='outDmlcStandbyperCurr'){
		outDmlcStandbyperCurr(); 
		}
	if(reportName=='outDmlcStandbyperImporter'){
		outDmlcStandbyperImporter(); 
		}
	if(reportName=='outDmlcUsanceperCurr'){
		outDmlcUsanceperCurr(); 
		}
	if(reportName=='outDmlcUsanceperImporter'){
		outDmlcUsanceperImporter(); 
		}
	if(reportName=='ytdDmlcOpened'){
		ytdDmlcOpened(); 
		}
	if(reportName=='ytdDmlcOpenedClassifiedbyBankingPHP'){
		ytdDmlcOpenedClassifiedbyBankingPHP(); 
		}
	
//fxlc
	if(reportName=='fxlcOpenedfortheMonth'){
		fxlcOpenedfortheMonth(); 
		}
	if(reportName=='outFxlcCashperCurr'){
		outFxlcCashperCurr(); 
		}
	if(reportName=='outFxlcCashperImporter'){
		outFxlcCashperImporter(); 
		}
	if(reportName=='outFxlcSightperCurr'){
		outFxlcSightperCurr(); 
		}
	if(reportName=='outFxlcSightperImporter'){
		outFxlcSightperImporter(); 
		}
	if(reportName=='outFxlcStandbyperCurr'){
		outFxlcStandbyperCurr(); 
		}
	if(reportName=='outFxlcStandbyperImporter'){
		outFxlcStandbyperImporter(); 
		}
	if(reportName=='outFxlcUsanceperCurr'){
		outFxlcUsanceperCurr(); 
		}
	if(reportName=='outFxlcUsanceperImporter'){
		outFxlcUsanceperImporter(); 
		}
	if(reportName=='outInwardBillsforCollectionperCurr'){
		outInwardBillsforCollectionperCurr(); 
		}
	if(reportName=='quarterlyFxlcStandbyOpened'){
		quarterlyFxlcStandbyOpened(); 
		}
	if(reportName=='weeklyMaturingUsance'){
		weeklyMaturingUsance(); 
		}
	if(reportName=='yearEndFxlcOpenedperAdvising'){
		yearEndFxlcOpenedperAdvising(); 
		}
	if(reportName=='yearEndFxlcOpenedperConfirming'){
		yearEndFxlcOpenedperConfirming(); 
		}
	if(reportName=='yearEndFxlcOpenedperCountry'){
		yearEndFxlcOpenedperCountry(); 
		}
	if(reportName=='ytdFxlcOpened'){
		ytdFxlcOpened(); 
		}
	if(reportName=='ytdFxlcOpenedClassifiedbyBankinUSD'){
		ytdFxlcOpenedClassifiedbyBankinUSD(); 
		}
	if(reportName=='consolidatedReportFxlcOpenedForTheMonth'){
		consolidatedReportFxlcOpenedForTheMonth(); 
	}
	
//EXport
	if(reportName=='exportNegoperClient'){
		exportNegoperClient(); 
		}
	if(reportName=='exportNegoperCollectionBank'){
		exportNegoperCollectionBank(); 
		}
	if(reportName=='exportPaymentperClient'){
		exportPaymentperClient(); 
		}
	if(reportName=='outExportNegoForeign'){
		outExportNegoForeign(); 
		}
	if(reportName=='outExportNegoDomestic'){
		outExportNegoDomestic(); 
		}
	
}